#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$app = require __DIR__ . '/bootstrap/app.php';

use MiniLaravel\Console\Kernel;

$kernel = new Kernel($app);
$kernel->handle($argv);
